"""Backtest engine for the 'nothing ever happens' No-bias Polymarket strategy.

This module is intentionally self-contained so it can be used both by the live
bot for offline evaluation and by ``optimizer.py`` during the Karpathy-style
autoresearch loop.

Data pipeline (priority order):

1. Parquet files under ``--data-dir`` (default ``data/polymarket``) from
   https://github.com/jon-becker/prediction-market-analysis (2026 clean
   Polymarket dataset).
2. CSV fallback under the same directory for Kaggle Polymarket dumps.
3. Synthetic fixture data generated by ``--synthetic`` (used by tests / smoke
   runs when no real dataset is available).

Universe filter (mirrors the live bot's strategy):

* Only resolved markets (``resolved == True``)
* Only standalone binary yes/no markets
* Category / title must not match any configured blacklist entry (default:
  "sports", "nba", "nfl", "football")
* Market duration (``end_date - start_date``) >= ``min_market_days``

Simulation:

* Enter **one** NO position per qualifying market at the first observed no-ask
  below ``no_price_cap`` after the ``min_market_days`` cooldown. Entry price is
  adjusted up by the configured slippage percentage.
* Position size = ``position_size_pct`` of the current bankroll, capped so
  concurrent notional stays under ``max_open_positions_pct`` of the bankroll.
* Hard ceiling of ``max_trade_count_per_day`` new entries per calendar day.
* Exit when the NO mid-price reaches ``exit_threshold`` (take-profit) or at
  resolution, whichever comes first. YES resolution = NO pays 1.0, NO resolves
  = position stops out at 0. A ``taker_fee_pct`` is charged on both legs.

Metrics output (see :class:`BacktestResult`):

* Total PnL (USD), Win Rate %, Sharpe Ratio (annualised), Max Drawdown %, Trade
  Count, Avg Hold Days.

Usage:

    python backtest.py --data-dir data/polymarket --config config.json

or from Python:

    from backtest import BacktestEngine, BacktestParams
    engine = BacktestEngine.from_directory("data/polymarket")
    result = engine.run(BacktestParams())
    print(result.summary_dict())
"""

from __future__ import annotations

import argparse
import json
import logging
import math
import os
import sys
from dataclasses import asdict, dataclass, field
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Iterable, Iterator, Sequence

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

DEFAULT_BLACKLIST: tuple[str, ...] = ("sports", "nba", "nfl", "football")

# Column aliases we'll accept across dataset variants.
_COLUMN_ALIASES: dict[str, tuple[str, ...]] = {
    "market_id": ("market_id", "id", "condition_id", "conditionId", "slug"),
    "title": ("title", "question", "name"),
    "category": ("category", "tag", "tags", "group", "groupItemTitle"),
    "start_date": ("start_date", "startDate", "created_at", "createdAt"),
    "end_date": ("end_date", "endDate", "closeDate", "resolutionDate"),
    "resolved": ("resolved", "isResolved", "closed", "is_closed"),
    "outcome": ("outcome", "winner", "resolution", "resolved_outcome"),
    "no_entry_price": (
        "no_entry_price",
        "no_price",
        "entry_no_price",
        "open_no_price",
        "initial_no_price",
    ),
    "no_peak_price": ("no_peak_price", "max_no_price", "no_high", "peak_no_price"),
    "yes_entry_price": (
        "yes_entry_price",
        "yes_price",
        "initial_yes_price",
        "open_yes_price",
    ),
    "yes_peak_price": ("yes_peak_price", "max_yes_price", "yes_high", "peak_yes_price"),
    "binary": ("binary", "is_binary", "yesno", "yes_no"),
}


@dataclass
class BacktestParams:
    """Tunable knobs — mirror of :class:`bot.config.NothingHappensConfig`
    fields that affect trade selection and sizing."""

    no_price_cap: float = 0.60
    min_market_days: int = 30
    max_open_positions_pct: float = 40.0
    position_size_pct: float = 2.0
    exit_threshold: float = 0.85
    max_trade_count_per_day: int = 5
    categories_blacklist: tuple[str, ...] = DEFAULT_BLACKLIST
    taker_fee_pct: float = 0.5  # 0.5% per leg
    slippage_pct: float = 0.2   # 0.2% worst-case slippage
    starting_bankroll_usd: float = 10_000.0
    min_hold_days: int = 1

    @classmethod
    def from_config_dict(cls, cfg: dict[str, Any]) -> "BacktestParams":
        strat = (cfg.get("strategies") or {}).get("nothing_happens") or {}
        back = cfg.get("backtest") or {}
        blacklist = strat.get("categories_blacklist") or DEFAULT_BLACKLIST
        if isinstance(blacklist, str):
            blacklist = [p.strip().lower() for p in blacklist.split(",") if p.strip()]
        return cls(
            no_price_cap=float(strat.get("no_price_cap", 0.60)),
            min_market_days=int(strat.get("min_market_days", 30)),
            max_open_positions_pct=float(strat.get("max_open_positions_pct", 40.0)),
            position_size_pct=float(strat.get("position_size_pct", 2.0)),
            exit_threshold=float(strat.get("exit_threshold", 0.85)),
            max_trade_count_per_day=int(strat.get("max_trade_count_per_day", 5)),
            categories_blacklist=tuple(str(c).lower() for c in blacklist),
            taker_fee_pct=float(back.get("taker_fee_pct", 0.5)),
            slippage_pct=float(back.get("slippage_pct", 0.2)),
            starting_bankroll_usd=float(back.get("starting_bankroll_usd", 10_000.0)),
            min_hold_days=int(back.get("min_hold_days", 1)),
        )


@dataclass
class Trade:
    market_id: str
    title: str
    category: str
    entry_date: date
    exit_date: date
    entry_price: float
    exit_price: float
    size_usd: float
    shares: float
    fees_usd: float
    pnl_usd: float
    hold_days: int
    exit_reason: str  # "take_profit" | "resolved_no" | "resolved_yes"
    won: bool

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["entry_date"] = self.entry_date.isoformat()
        d["exit_date"] = self.exit_date.isoformat()
        return d


@dataclass
class BacktestResult:
    total_pnl_usd: float
    win_rate_pct: float
    sharpe_ratio: float
    max_drawdown_pct: float
    trade_count: int
    avg_hold_days: float
    final_bankroll_usd: float
    starting_bankroll_usd: float
    trades: list[Trade] = field(default_factory=list)
    equity_curve: list[tuple[str, float]] = field(default_factory=list)

    def summary_dict(self) -> dict[str, Any]:
        return {
            "total_pnl_usd": round(self.total_pnl_usd, 2),
            "win_rate_pct": round(self.win_rate_pct, 2),
            "sharpe_ratio": round(self.sharpe_ratio, 3),
            "max_drawdown_pct": round(self.max_drawdown_pct, 2),
            "trade_count": self.trade_count,
            "avg_hold_days": round(self.avg_hold_days, 2),
            "final_bankroll_usd": round(self.final_bankroll_usd, 2),
            "starting_bankroll_usd": round(self.starting_bankroll_usd, 2),
            "return_pct": round(
                (self.final_bankroll_usd / self.starting_bankroll_usd - 1.0) * 100.0, 2
            )
            if self.starting_bankroll_usd
            else 0.0,
        }


def _resolve_column(df: pd.DataFrame, logical: str) -> str | None:
    for candidate in _COLUMN_ALIASES.get(logical, ()):  # noqa: E501
        if candidate in df.columns:
            return candidate
    return None


def _coerce_date(value: Any) -> date | None:
    if value is None:
        return None
    if isinstance(value, pd.Timestamp):
        return value.date() if not pd.isna(value) else None
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    if isinstance(value, (int, float)):
        if math.isnan(float(value)):
            return None
        # assume seconds unless it looks like ms
        ts = float(value)
        if ts > 10**12:
            ts /= 1000.0
        try:
            return datetime.fromtimestamp(ts, tz=timezone.utc).date()
        except (OverflowError, OSError, ValueError):
            return None
    s = str(value).strip()
    if not s or s.lower() in {"nan", "none", "null"}:
        return None
    try:
        return datetime.fromisoformat(s.replace("Z", "+00:00")).date()
    except ValueError:
        for fmt in ("%Y-%m-%d", "%Y-%m-%d %H:%M:%S", "%m/%d/%Y"):
            try:
                return datetime.strptime(s, fmt).date()
            except ValueError:
                continue
    return None


def _coerce_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return bool(value)
    if value is None:
        return False
    return str(value).strip().lower() in {"1", "true", "yes", "y", "resolved", "closed"}


def _coerce_float(value: Any, default: float = float("nan")) -> float:
    try:
        f = float(value)
    except (TypeError, ValueError):
        return default
    return f if not math.isnan(f) else default


def _coerce_str(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, float) and math.isnan(value):
        return ""
    return str(value).strip()


def _normalize_market_row(row: dict[str, Any], columns: dict[str, str | None]) -> dict[str, Any] | None:
    def get(key: str) -> Any:
        col = columns.get(key)
        return row.get(col) if col else None

    market_id = _coerce_str(get("market_id"))
    if not market_id:
        return None

    start = _coerce_date(get("start_date"))
    end = _coerce_date(get("end_date"))
    if end is None:
        return None
    if start is None:
        # Some dumps only give end_date; assume a 60-day window so the duration
        # filter still makes sense for short-horizon markets.
        start = end - timedelta(days=60)

    title = _coerce_str(get("title"))
    category = _coerce_str(get("category"))
    outcome = _coerce_str(get("outcome")).lower()
    resolved_raw = get("resolved")
    resolved = _coerce_bool(resolved_raw) if resolved_raw is not None else bool(outcome)

    binary_raw = get("binary")
    binary = True if binary_raw is None else _coerce_bool(binary_raw)

    no_entry = _coerce_float(get("no_entry_price"))
    yes_entry = _coerce_float(get("yes_entry_price"))
    if math.isnan(no_entry) and not math.isnan(yes_entry):
        no_entry = max(0.0, min(1.0, 1.0 - yes_entry))
    no_peak = _coerce_float(get("no_peak_price"))
    yes_peak = _coerce_float(get("yes_peak_price"))
    if math.isnan(no_peak) and not math.isnan(yes_peak):
        no_peak = max(0.0, min(1.0, 1.0 - yes_peak))

    return {
        "market_id": market_id,
        "title": title,
        "category": category,
        "start_date": start,
        "end_date": end,
        "resolved": resolved,
        "outcome": outcome,
        "no_entry_price": no_entry,
        "no_peak_price": no_peak,
        "binary": binary,
    }


def load_markets(
    data_dir: Path | str,
    *,
    max_files: int | None = None,
) -> pd.DataFrame:
    """Load and normalise market rows from parquet/csv dumps under ``data_dir``.

    The loader is intentionally forgiving about column naming so the 2026
    jon-becker parquet format and older Kaggle CSV exports both work."""

    data_dir = Path(data_dir)
    if not data_dir.exists():
        raise FileNotFoundError(
            f"Backtest data directory not found: {data_dir}. "
            f"Download from https://github.com/jon-becker/prediction-market-analysis "
            f"and extract into this directory."
        )

    parquet_files = sorted(data_dir.rglob("*.parquet"))
    csv_files = sorted(data_dir.rglob("*.csv"))
    files: list[Path] = parquet_files + csv_files
    if max_files:
        files = files[:max_files]
    if not files:
        raise FileNotFoundError(
            f"No .parquet or .csv files found under {data_dir}. "
            "Run scripts/fetch_prediction_market_analysis.sh or drop files in manually."
        )

    frames: list[pd.DataFrame] = []
    for f in files:
        try:
            if f.suffix == ".parquet":
                frames.append(pd.read_parquet(f))
            else:
                frames.append(pd.read_csv(f))
        except Exception as exc:  # pragma: no cover - dataset quirks
            logger.warning("Skipping %s: %s", f, exc)

    if not frames:
        raise RuntimeError("All data files failed to load")

    df = pd.concat(frames, ignore_index=True, sort=False)
    columns = {logical: _resolve_column(df, logical) for logical in _COLUMN_ALIASES}
    if not columns.get("market_id") or not columns.get("end_date"):
        raise ValueError(
            "Could not resolve required columns (market_id/end_date) in loaded data. "
            f"Available columns: {list(df.columns)}"
        )

    normalized: list[dict[str, Any]] = []
    for row in df.to_dict(orient="records"):
        n = _normalize_market_row(row, columns)
        if n is not None:
            normalized.append(n)

    out = pd.DataFrame(normalized)
    if out.empty:
        return out
    out.sort_values("end_date", inplace=True)
    out.reset_index(drop=True, inplace=True)
    return out


def filter_markets(
    df: pd.DataFrame,
    *,
    min_market_days: int,
    categories_blacklist: Sequence[str],
    require_resolved: bool = True,
) -> pd.DataFrame:
    if df.empty:
        return df
    mask = df["binary"].astype(bool)
    if require_resolved:
        mask &= df["resolved"].astype(bool)
    duration = (
        pd.to_datetime(df["end_date"]) - pd.to_datetime(df["start_date"])
    ).dt.days
    mask &= duration >= int(min_market_days)

    blacklist = tuple(b.lower() for b in categories_blacklist if b)
    if blacklist:
        def _not_blacklisted(row: pd.Series) -> bool:
            blob = f"{row.get('title', '')} {row.get('category', '')}".lower()
            return not any(b in blob for b in blacklist)

        mask &= df.apply(_not_blacklisted, axis=1)

    out = df.loc[mask].copy()
    out.reset_index(drop=True, inplace=True)
    return out


def _sharpe(returns: Sequence[float], *, periods_per_year: float = 252.0) -> float:
    if not returns:
        return 0.0
    arr = np.asarray(list(returns), dtype=float)
    if arr.size < 2:
        return 0.0
    std = float(arr.std(ddof=1))
    if std <= 1e-12:
        return 0.0
    return float(arr.mean() / std * math.sqrt(periods_per_year))


def _max_drawdown_pct(equity: Sequence[float]) -> float:
    if not equity:
        return 0.0
    arr = np.asarray(list(equity), dtype=float)
    peak = np.maximum.accumulate(arr)
    with np.errstate(divide="ignore", invalid="ignore"):
        dd = np.where(peak > 0, (peak - arr) / peak, 0.0)
    return float(dd.max() * 100.0) if dd.size else 0.0


class BacktestEngine:
    """Realistic simulation of the No-bias strategy over a filtered market
    universe."""

    def __init__(self, markets: pd.DataFrame):
        self.markets = markets

    @classmethod
    def from_directory(
        cls,
        data_dir: Path | str,
        *,
        max_files: int | None = None,
    ) -> "BacktestEngine":
        return cls(load_markets(data_dir, max_files=max_files))

    @classmethod
    def from_dataframe(cls, df: pd.DataFrame) -> "BacktestEngine":
        return cls(df.copy().reset_index(drop=True))

    def _qualify(self, params: BacktestParams) -> pd.DataFrame:
        return filter_markets(
            self.markets,
            min_market_days=params.min_market_days,
            categories_blacklist=params.categories_blacklist,
        )

    def run(
        self,
        params: BacktestParams,
        *,
        start: date | None = None,
        end: date | None = None,
    ) -> BacktestResult:
        qualified = self._qualify(params)
        if start is not None:
            qualified = qualified[qualified["end_date"] >= start]
        if end is not None:
            qualified = qualified[qualified["end_date"] <= end]
        qualified = qualified.sort_values("end_date").reset_index(drop=True)

        bankroll = params.starting_bankroll_usd
        open_notional = 0.0
        trades: list[Trade] = []
        equity_curve: list[tuple[str, float]] = []
        trades_per_day: dict[date, int] = {}

        fee = params.taker_fee_pct / 100.0
        slip = params.slippage_pct / 100.0
        cap = params.no_price_cap
        exit_thr = params.exit_threshold
        pos_frac = params.position_size_pct / 100.0
        max_open_frac = params.max_open_positions_pct / 100.0

        for _, row in qualified.iterrows():
            entry_day = max(
                row["start_date"] + timedelta(days=max(params.min_market_days, params.min_hold_days)),
                row["start_date"] + timedelta(days=params.min_hold_days),
            )
            if entry_day >= row["end_date"]:
                continue

            raw_entry = row["no_entry_price"]
            if math.isnan(raw_entry) or raw_entry <= 0.0 or raw_entry > cap:
                continue
            # Worst-case fill: entry bumped up by slippage, capped at 0.99.
            entry_price = min(0.99, raw_entry * (1.0 + slip))
            if entry_price > cap:
                continue

            count_today = trades_per_day.get(entry_day, 0)
            if count_today >= params.max_trade_count_per_day:
                continue

            # Sizing: % of bankroll, capped by remaining concurrent-exposure budget.
            size_usd = bankroll * pos_frac
            remaining_budget = max(0.0, bankroll * max_open_frac - open_notional)
            size_usd = min(size_usd, remaining_budget)
            if size_usd < 5.0:
                continue

            shares = size_usd / entry_price
            entry_fees = size_usd * fee

            peak = row["no_peak_price"]
            outcome = str(row["outcome"]).lower()
            hit_take_profit = (
                not math.isnan(peak) and peak >= exit_thr and outcome != "yes"
            )

            if hit_take_profit:
                exit_price = exit_thr * (1.0 - slip)  # selling into bids, slippage down
                exit_reason = "take_profit"
                exit_day = entry_day + timedelta(
                    days=max(1, int((row["end_date"] - entry_day).days * 0.5))
                )
                won = True
            elif outcome == "no":
                exit_price = 1.0
                exit_reason = "resolved_no"
                exit_day = row["end_date"]
                won = True
            else:
                exit_price = 0.0
                exit_reason = "resolved_yes"
                exit_day = row["end_date"]
                won = False

            gross = shares * exit_price
            exit_fees = gross * fee
            pnl = gross - size_usd - entry_fees - exit_fees

            bankroll += pnl
            open_notional = max(0.0, open_notional)  # cleared synchronously in this sim
            trades_per_day[entry_day] = count_today + 1
            hold_days = max(1, (exit_day - entry_day).days)

            trades.append(
                Trade(
                    market_id=row["market_id"],
                    title=row["title"],
                    category=row["category"],
                    entry_date=entry_day,
                    exit_date=exit_day,
                    entry_price=entry_price,
                    exit_price=exit_price,
                    size_usd=size_usd,
                    shares=shares,
                    fees_usd=entry_fees + exit_fees,
                    pnl_usd=pnl,
                    hold_days=hold_days,
                    exit_reason=exit_reason,
                    won=won,
                )
            )
            equity_curve.append((exit_day.isoformat(), bankroll))

        if not trades:
            return BacktestResult(
                total_pnl_usd=0.0,
                win_rate_pct=0.0,
                sharpe_ratio=0.0,
                max_drawdown_pct=0.0,
                trade_count=0,
                avg_hold_days=0.0,
                final_bankroll_usd=bankroll,
                starting_bankroll_usd=params.starting_bankroll_usd,
                trades=[],
                equity_curve=[],
            )

        returns = [t.pnl_usd / t.size_usd for t in trades if t.size_usd > 0]
        wins = sum(1 for t in trades if t.won)
        equity_vals = [v for _, v in equity_curve]

        return BacktestResult(
            total_pnl_usd=sum(t.pnl_usd for t in trades),
            win_rate_pct=wins / len(trades) * 100.0,
            sharpe_ratio=_sharpe(returns),
            max_drawdown_pct=_max_drawdown_pct(equity_vals),
            trade_count=len(trades),
            avg_hold_days=sum(t.hold_days for t in trades) / len(trades),
            final_bankroll_usd=bankroll,
            starting_bankroll_usd=params.starting_bankroll_usd,
            trades=trades,
            equity_curve=equity_curve,
        )

    def walk_forward(
        self,
        params: BacktestParams,
        *,
        splits: int = 4,
    ) -> list[BacktestResult]:
        """Split markets into ``splits`` chronological folds; evaluate
        strictly out-of-sample on each fold (the first fold is in-sample only
        and used for "baseline" reference)."""

        qualified = self._qualify(params)
        if qualified.empty:
            return []

        qualified = qualified.sort_values("end_date").reset_index(drop=True)
        end_dates = pd.to_datetime(qualified["end_date"])
        total = len(qualified)
        fold = max(1, total // splits)
        results: list[BacktestResult] = []
        for i in range(splits):
            lo = i * fold
            hi = total if i == splits - 1 else (i + 1) * fold
            if lo >= hi:
                continue
            start = end_dates.iloc[lo].date()
            stop = end_dates.iloc[hi - 1].date()
            results.append(self.run(params, start=start, end=stop))
        return results


# ---------------------------------------------------------------------------
# Synthetic fixture data for smoke tests and local development
# ---------------------------------------------------------------------------


def generate_synthetic_markets(
    *,
    n: int = 500,
    seed: int = 42,
    start: date = date(2024, 1, 1),
) -> pd.DataFrame:
    """Generate a deterministic synthetic universe that roughly matches the
    empirical No-bias edge: ~72% of non-sports markets resolve NO. Useful for
    offline unit tests and smoke runs when real parquet data isn't present."""

    rng = np.random.default_rng(seed)
    categories = [
        "politics",
        "tech",
        "macro",
        "entertainment",
        "crypto",
        "sports",
        "nba",
        "nfl",
    ]
    rows = []
    for i in range(n):
        cat = categories[int(rng.integers(0, len(categories)))]
        duration = int(rng.integers(7, 120))
        start_d = start + timedelta(days=int(rng.integers(0, 400)))
        end_d = start_d + timedelta(days=duration)
        is_sport = cat in {"sports", "nba", "nfl", "football"}
        # No-bias edge: non-sports resolve NO with ~0.72 probability.
        no_prob = 0.52 if is_sport else 0.72
        outcome = "no" if rng.random() < no_prob else "yes"
        no_entry = float(rng.uniform(0.35, 0.85))
        # If market will resolve no, peak probably climbs high before close.
        no_peak = min(0.99, no_entry + float(rng.uniform(0.0, 0.45)))
        if outcome == "yes":
            no_peak = min(no_peak, 0.9)
        rows.append(
            {
                "market_id": f"syn-{i:05d}",
                "title": f"{cat.title()} synthetic market #{i}",
                "category": cat,
                "start_date": start_d,
                "end_date": end_d,
                "resolved": True,
                "outcome": outcome,
                "no_entry_price": no_entry,
                "no_peak_price": no_peak,
                "binary": True,
            }
        )
    return pd.DataFrame(rows)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _load_config_file(path: Path | str) -> dict[str, Any]:
    p = Path(path)
    if not p.exists():
        return {}
    with p.open() as f:
        return json.load(f)


def _parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--data-dir",
        default=os.getenv("POLYMARKET_DATA_DIR", "data/polymarket"),
        help="Directory with .parquet / .csv market dumps (default: %(default)s).",
    )
    parser.add_argument(
        "--config",
        default="config.json",
        help="Path to config.json (falls back to config.example.json).",
    )
    parser.add_argument(
        "--synthetic",
        action="store_true",
        help="Use deterministic synthetic data (offline smoke test).",
    )
    parser.add_argument(
        "--synthetic-n",
        type=int,
        default=500,
        help="Number of synthetic markets to generate (default: %(default)s).",
    )
    parser.add_argument(
        "--walk-forward-splits",
        type=int,
        default=0,
        help="If > 0, print per-fold walk-forward metrics as well.",
    )
    parser.add_argument(
        "--output-json",
        default=None,
        help="Optional path to write the summary dict as JSON.",
    )
    parser.add_argument(
        "--max-files",
        type=int,
        default=None,
        help="Optional cap on number of data files to read (useful for quick smoke runs).",
    )
    return parser.parse_args(list(argv) if argv is not None else None)


def main(argv: Sequence[str] | None = None) -> int:
    logging.basicConfig(
        level=os.getenv("LOG_LEVEL", "INFO"),
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    args = _parse_args(argv)
    cfg = _load_config_file(args.config) or _load_config_file("config.example.json")
    params = BacktestParams.from_config_dict(cfg)

    if args.synthetic:
        engine = BacktestEngine.from_dataframe(
            generate_synthetic_markets(n=args.synthetic_n)
        )
    else:
        engine = BacktestEngine.from_directory(args.data_dir, max_files=args.max_files)

    result = engine.run(params)
    summary = result.summary_dict()
    print(json.dumps({"params": asdict(params), "result": summary}, indent=2, default=str))

    if args.walk_forward_splits and args.walk_forward_splits > 1:
        folds = engine.walk_forward(params, splits=args.walk_forward_splits)
        print(json.dumps(
            {
                "walk_forward": [r.summary_dict() for r in folds],
            },
            indent=2,
        ))

    if args.output_json:
        Path(args.output_json).parent.mkdir(parents=True, exist_ok=True)
        with open(args.output_json, "w") as f:
            json.dump({"params": asdict(params), "result": summary}, f, indent=2, default=str)

    return 0


if __name__ == "__main__":
    sys.exit(main())
